server:
  servlet:
    context-path: /records
  port: 8080

spring:
  application:
    name: records-admin

mybatis:

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: records-chanfa-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: ''  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /actuator/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时